echo "Welcome to Archlinux container"
echo "You can operate OS as usually. All progress will be lost when you stop container or log out from DE inside container."
echo ""
echo "Default passwords for accounts:"
echo "headless:archlinux"
echo "root:archlinux"
